import './globals.css';
import Navigator from './Navigator';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout ({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body>
    <Navigator />
    {children}
    </body>
    </html>
  );
}
